from __future__ import annotations

from dataclasses import dataclass, replace


@dataclass(frozen=True)
class PageGuide:
    section: str
    path: str
    title: str
    icon: str
    summary: str
    contents: str
    reader_action: str
    api: str
    output: str
    default: bool = False
    url_path: str | None = None
    interactive: bool = False
    area: str = "Reference"
    lesson: int = 0
    manual: str = ""
    lab: str = ""
    learning_objectives: tuple[str, ...] = ()


REFERENCE_AND_DEMO_PAGES: tuple[PageGuide, ...] = (
    PageGuide(
        section="Documentation",
        path="docs/project_overview.py",
        title="Readme",
        icon=":material/home:",
        summary="Start here for the project purpose, local installation, and first working graph.",
        contents="The README, library stack, quick-start graph, record-conversion tables, public API reference, and local run commands.",
        reader_action="Select a node in the quick-start graph and compare the returned dictionary with the source records shown above it.",
        api="graph_workbench, NodeStyle, EdgeStyle, dataframe_to_records, records_to_dataframe",
        output="A live graph event dictionary plus dataframe and record-conversion results.",
        url_path="readme",
        interactive=True,
    ),
    PageGuide(
        section="Documentation",
        path="docs/element_contract.py",
        title="Graph Data Format",
        icon=":material/schema:",
        summary="Learn the node and edge dictionary contract before building larger examples.",
        contents="The minimum graph, required IDs and endpoints, optional business fields, expansion metadata, validation rules, and Python-to-browser flow.",
        reader_action="Trace one vehicle-to-location edge and inspect how its source and target IDs refer to node records.",
        api="Element, ElementId, ElementIdInput, Elements, validate_elements",
        output="Annotated node and edge dictionaries with validation examples.",
    ),
    PageGuide(
        section="Documentation",
        path="docs/styling_guide.py",
        title="Styling Guide",
        icon=":material/palette:",
        summary="Understand the simple Python style helpers and advanced selector rules.",
        contents="NodeStyle, EdgeStyle, StyleRule, Cytoscape selectors, and a guided reading of the frontend style conversion.",
        reader_action="Compare a label-based helper style with a selector rule for a high-priority entity.",
        api="NodeStyle, EdgeStyle, StyleRule, node_styles, edge_styles",
        output="Python style definitions and the Cytoscape properties they produce.",
    ),
    PageGuide(
        section="Documentation",
        path="docs/frontend_architecture.py",
        title="Frontend Architecture",
        icon=":material/developer_board:",
        summary="Follow how Python data and options become browser-side Cytoscape behavior.",
        contents="The update lifecycle, JavaScript glossary, module-to-API map, option reconciliation, layout guards, Components v2 state, and returned events.",
        reader_action="Follow one selection or CRUD event from the JavaScript module back to the Streamlit return value.",
        api="graph_workbench, Event, graph_commands, Components v2 state and triggers",
        output="Architecture diagrams in prose, annotated snippets, and a scrollable JavaScript capability map.",
    ),
    PageGuide(
        section="Documentation",
        path="docs/interactive_crud.py",
        title="Interactive CRUD",
        icon=":material/edit_document:",
        summary="Learn the Python-owned state pattern behind safe graph editing and data loading.",
        contents="The CRUD mental model, returned event shape, Streamlit dialogs, session-state updates, helper functions, and incremental commands.",
        reader_action="Trace a create-node intent through validation, Python state mutation, and the next graph render.",
        api="CrudAction, apply_graph_command, upsert_elements, graph_commands",
        output="Annotated CRUD dictionaries and a complete state-handling code pattern.",
        url_path="interactive-crud-docs",
    ),
    PageGuide(
        section="Documentation",
        path="docs/changelog.py",
        title="Changelog",
        icon=":material/history:",
        summary="Review the implemented features, fixes, and compatibility changes by release.",
        contents="The project changelog rendered as release-oriented documentation.",
        reader_action="Use it to identify when an API or interaction changed before updating consuming code.",
        api="Release history",
        output="Versioned feature and fix notes.",
    ),
    PageGuide(
        section="Documentation",
        path="docs/supported_icons.py",
        title="Supported Icons",
        icon=":material/category:",
        summary="Browse the packaged icon names available to node styles.",
        contents="A searchable visual catalog of the Material Symbol assets shipped with the component.",
        reader_action="Find an icon that matches a record category and use its name in NodeStyle.",
        api="NodeStyle(icon=...), supported icon assets",
        output="A preview table containing icon names and rendered images.",
    ),
    PageGuide(
        section="Demos",
        path="demos/demo_overview.py",
        title="Feature finder",
        icon=":material/dashboard:",
        summary="Find a working playground for the feature you want to explore.",
        contents="Searchable feature examples with links to the interactive playgrounds.",
        reader_action="Choose a feature and open its working example.",
        api="Complete st-graph-workbench public surface",
        output="A page-by-page guide and capability-to-demo map.",
    ),
    PageGuide(
        section="Demos",
        path="demos/branch_expansion.py",
        title="Branch Exploration",
        icon=":material/account_tree:",
        summary="Explore independent branches while retaining shared records and source data.",
        contents="Paginated expansion, collapse, shared records, bulk limits, analysis scopes, search restoration, cached edits and snapshots.",
        reader_action="Expand both locations, close one branch, and inspect why the shared report remains.",
        api="ExpansionConfig, ExpansionController, ExpansionOperation, ExpansionProvider, ExpansionRequest, ExpansionResponse, InMemoryExpansionProvider",
        output="Displayed and loaded graphs, change records, scoped analysis and reproducible snapshots.",
        interactive=True,
    ),
    PageGuide(
        section="Demos",
        path="demos/graph_workbench_showcase.py",
        title="Graph Workbench Showcase",
        icon=":material/account_tree:",
        summary="See the main graph workspace features operating together on connected sample records.",
        contents="Source records, styled entities and relationships, search, selection, expansion, analysis, export, viewport tools, and returned dictionaries.",
        reader_action="Search for an entity, select connected evidence, expand a node from its context menu, and inspect the returned event.",
        api="graph_workbench and the main interaction options",
        output="Selection, expansion, analysis, visibility, export, and viewport event dictionaries.",
        interactive=True,
    ),
    PageGuide(
        section="Demos",
        path="demos/data_helpers_commands.py",
        title="Data Helpers And Commands",
        icon=":material/database:",
        summary="Move between tables, records, graph elements, Python mutations, and browser commands.",
        contents="Vehicle sighting records, conversion options, packaged JSON graph loading, validation, pure Python helpers, a command playground, current graph state, and executed output.",
        reader_action="Round-trip the evidence table, apply each helper, then send add, update, delete, layout, and viewport commands.",
        api="dataframe_to_records, records_to_dataframe, validate_elements, element helpers, command builders and appliers",
        output="Dataframes, loaded JSON records, validated elements, command dictionaries, and component events.",
        interactive=True,
    ),
    PageGuide(
        section="Demos",
        path="demos/node_style.py",
        title="Node Styles",
        icon=":material/radio_button_checked:",
        summary="Control how your record categories are represented as graph nodes.",
        contents="The source nodes, controls for icon, caption, color, shape, size, border, opacity, label position, and the executed style payload.",
        reader_action="Change one visual property at a time and compare the graph with the NodeStyle dictionary.",
        api="NodeStyle, StyleRule, node_styles",
        output="The styled graph and the returned component dictionary.",
        interactive=True,
    ),
    PageGuide(
        section="Demos",
        path="demos/edge_style.py",
        title="Edge Styles",
        icon=":material/arrow_right_alt:",
        summary="Control how relationships communicate direction, type, and confidence.",
        contents="The source edges, controls for captions, arrows, width, line and curve style, opacity, color, and the executed style payload.",
        reader_action="Compare directed, dashed, dotted, and curved relationships against their EdgeStyle definitions.",
        api="EdgeStyle, StyleRule, edge_styles",
        output="The styled relationship graph and returned component dictionary.",
        interactive=True,
    ),
    PageGuide(
        section="Demos",
        path="demos/layout.py",
        title="Layout Algorithms",
        icon=":material/hub:",
        summary="Compare graph layouts and understand when each algorithm is useful.",
        contents="The same source graph rendered with preset, cose, fcose, dagre, cola, grid, circle, concentric, breadthfirst, and random options.",
        reader_action="Switch layouts, tune fit and padding, and compare the resulting positions without changing the data.",
        api="layout string or layout dictionary, run_layout command",
        output="The active layout payload, positioned graph, and returned component value.",
        interactive=True,
    ),
    PageGuide(
        section="Demos",
        path="demos/investigation_tools.py",
        title="Investigation Tools",
        icon=":material/search:",
        summary="Explore connected records through selection, search, visibility, and analysis.",
        contents="Vehicles, people, times, cameras, devices and locations; box selection; search modes; neighbor filters; exports; positions; every analysis action; and returned records flattened into a dataframe.",
        reader_action="Box-select evidence, clear or toggle selection, search properties, run shortest path and degree, then inspect the returned records.",
        api="selection_mode, return_selection, show_selection_details, connected_drag, search, node_actions, analysis_actions, return_positions",
        output="Selection, search, visibility, analysis, and position dictionaries plus a dataframe of returned element records.",
        interactive=True,
    ),
    PageGuide(
        section="Demos",
        path="demos/node_actions.py",
        title="Node Actions",
        icon=":material/touch_app:",
        summary="Demonstrate progressive expansion, collapse, removal, and neighborhood actions.",
        contents="Available expansion records, badge metadata, right-click actions, hidden-neighbor controls, graph changes, and saved positions.",
        reader_action="Right-click a node to expand or collapse it, confirm badge counts, and inspect the action returned to Python.",
        api="NodeAction, node_actions, node.data.expansion, elements_sync",
        output="Expansion, collapse, removal, visibility, and position dictionaries.",
        interactive=True,
    ),
    PageGuide(
        section="Demos",
        path="demos/compound_performance.py",
        title="Compound And Performance",
        icon=":material/layers:",
        summary="Group related entities and tune rendering for larger or denser graphs.",
        contents="Compound parent nodes, child entities, performance profiles, source data, rendered graph, returned value, and browser implementation notes.",
        reader_action="Compare parent grouping and switch between default, large, and dense profiles.",
        api="node.data.parent, performance_profile, StyleRule",
        output="The compound graph, profile configuration, and returned component dictionary.",
        interactive=True,
    ),
    PageGuide(
        section="Demos",
        path="demos/progressive_loading.py",
        title="Progressive Loading",
        icon=":material/playlist_add:",
        summary="Grow a large graph in bounded batches without replacing the browser canvas.",
        contents="Visible source records, explained Load more callbacks, cross-location sightings, BFS and shortest-path experiments, clearing highlights, result tables, CSV exports, and scope limitations.",
        reader_action="Compare one-node BFS with a two-node shortest path; load sightings to connect the groups, then clear analysis highlights without discarding saved results.",
        api="ProgressiveLoadConfig, ConnectedDragConfig, progressive_loading, connected_drag, add_elements_command, elements_sync, performance_profile, analysis_actions, records_to_dataframe",
        output="Load-more events, increasing graph counts, and checkpoint-labelled BFS visits and shortest-path relationship records with CSV export.",
        url_path="progressive_loading",
        interactive=True,
    ),
    PageGuide(
        section="Demos",
        path="demos/interactive_crud.py",
        title="Interactive CRUD / Data Loading",
        icon=":material/edit:",
        summary="Run complete create, read, update, delete, and related-data workflows.",
        contents="Python-owned graph tables, CRUD dialogs, selected-record context, data loading, command-driven updates, reader checks, and returned dictionaries.",
        reader_action="Add a node in the dialog, connect it with an edge, update it, load related records, and delete it while watching Python state.",
        api="crud_actions, graph_commands, apply_graph_command, st.session_state",
        output="CRUD intent dictionaries, command dictionaries, and updated node and edge tables.",
        url_path="crud_data_loading",
        interactive=True,
    ),
    PageGuide(
        section="Demos",
        path="demos/progressive_loading_scale.py",
        title="Progressive Loading Scale Test",
        icon=":material/speed:",
        summary="Measure how the same browser graph behaves as the loaded record count grows.",
        contents="Deterministic 100-to-10,000 record checkpoints, source samples, node and edge counts, the large rendering profile, Load more guidance, and a repeatable browser benchmark.",
        reader_action="Render several checkpoints, try search and selection, then run the benchmark to find a useful limit for your browser and dataset.",
        api="graph_workbench, ConnectedDragConfig, connected_drag, performance_profile, progressive_loading, records_to_dataframe",
        output="Rendered graph counts, source samples, returned interaction dictionaries, and machine-specific benchmark measurements.",
        url_path="progressive_loading_scale",
        interactive=True,
    ),
    PageGuide(
        section="Demos",
        path="demos/editing_viewport_tools.py",
        title="Editing And Viewport Tools",
        icon=":material/preview:",
        summary="Compare browser-local edits with viewport controls and Python-returned state.",
        contents="Source elements, edit actions, pan and zoom constraints, save/restore/reset view, graph commands, returned output, and reader checks.",
        reader_action="Add and connect nodes, lock or snap them, undo and redo, then save and restore the viewport.",
        api="edit_actions, viewport_actions, min_zoom, max_zoom, wheel_sensitivity, viewport commands",
        output="Edit, viewport, command, selection, and position dictionaries.",
        interactive=True,
    ),
    PageGuide(
        section="Demos",
        path="demos/event_listeners.py",
        title="Event Listeners",
        icon=":material/sensors:",
        summary="Return low-level Cytoscape interactions under application-specific event names.",
        contents="Event definitions, name validation and reserved actions, source graph records, click, tap, double-click checks, and the returned custom-event dictionary.",
        reader_action="Trigger each configured event on nodes and edges and compare target IDs and groups.",
        api="Event, events, on_change",
        output="Custom event dictionaries with action, type, target_id, target_group, and timestamp.",
        interactive=True,
    ),
    PageGuide(
        section="Demos",
        path="demos/component_v2_validation.py",
        title="Components V2 Validation",
        icon=":material/check_circle:",
        summary="Verify independent component instances and live option updates without remounting.",
        contents="Two graphs with separate keys, source data, dynamic selection and zoom options, expansion badges, event listeners, and returned values.",
        reader_action="Change the left graph options and confirm the right graph keeps independent selection, viewport, and event state.",
        api="stable key, Components v2 state, dynamic options, graph_workbench",
        output="Separate returned dictionaries for the left and right component instances.",
        interactive=True,
    ),
)


def _lesson(number, section, slug, title, summary, api, manual, lab, objectives):
    return PageGuide(
        section=section,
        path=f"tutorials/{slug}.py",
        title=title,
        icon=":material/school:",
        summary=summary,
        contents="Source data; code and working graph; returned data; common mistakes and next step.",
        reader_action=summary,
        api=api,
        output="A live graph and described source or returned dictionaries.",
        default=number == 1,
        url_path="" if number == 1 else f"learn_{slug}",
        interactive=True,
        area="Tutorials",
        lesson=number,
        manual=manual,
        lab=lab,
        learning_objectives=objectives,
    )


TUTORIAL_PAGES = (
    _lesson(
        1,
        "Foundations",
        "first_graph",
        "Build your first graph",
        "Turn connected records into an interactive graph using Python dictionaries. The same contract works for dependencies, networks, workflows, and other connected data.",
        "graph_workbench, validate_elements, Element, Elements, ElementId, ElementIdInput, ElementValidationError",
        "concepts/elements.md",
        "demos/data_helpers_commands.py",
        (
            "Build node and edge dictionaries with unique IDs and valid endpoints.",
            "Validate the input and render it with a stable component key.",
            "Distinguish the input graph from a returned interaction event.",
        ),
    ),
    _lesson(
        2,
        "Foundations",
        "change_records",
        "Change nodes and edges",
        "Read, add, update, and delete graph records while keeping Python in control of the data.",
        "get_element, upsert_elements, update_element_data, delete_elements",
        "guides/crud.md",
        "demos/data_helpers_commands.py",
        (
            "Retrieve, add, update, and delete a record by its ID using Python helpers.",
            "Keep the source table and graph synchronized with the accepted helper result.",
            "Check duplicate-safe upserts and removal of a node's incident edges.",
        ),
    ),
    _lesson(
        3,
        "Foundations",
        "style_graph",
        "Style your graph",
        "Give categories and relationships a readable visual identity, then highlight individual records.",
        "NodeStyle, EdgeStyle, StyleRule",
        "guides/styling-icons.md",
        "demos/node_style.py",
        (
            "Map record categories to node icons, captions, colors, sizes, and shapes.",
            "Style relationship direction and line appearance with EdgeStyle.",
            "Combine broad style defaults with targeted selector rules without changing data.",
        ),
    ),
    _lesson(
        4,
        "Foundations",
        "layouts",
        "Arrange and navigate",
        "Compare ten layouts on the same records and control how the viewport moves.",
        "Layout, ToolbarConfig, ViewportAction, viewport_command",
        "guides/rendering-layouts.md",
        "demos/layout.py",
        (
            "Compare all ten layouts without changing graph relationships.",
            "Distinguish node coordinates from camera movement and switch toolbar presentations without covering the canvas.",
            "Read returned positions and use preset layout and viewport controls appropriately.",
        ),
    ),
    _lesson(
        5,
        "Foundations",
        "load_data",
        "Load your own data",
        "Convert tables to records, construct a graph, and validate imported JSON before using it.",
        "Record, dataframe_to_records, records_to_dataframe, validate_elements, ElementValidationError",
        "concepts/records.md",
        "demos/data_helpers_commands.py",
        (
            "Convert between dataframes and records without confusing conversion with graph construction.",
            "Map source columns explicitly to node IDs, edge endpoints, and properties.",
            "Validate table and JSON imports before replacing the last accepted graph.",
        ),
    ),
    _lesson(
        6,
        "Exploration",
        "selection",
        "Select and use records",
        "Turn individual or grouped selections into source-record tables your application can use.",
        "SelectionMode, ConnectedDragConfig, GraphEvent",
        "guides/selection-search.md",
        "demos/investigation_tools.py",
        (
            "Select and deselect nodes or edges in single, multiple, and box modes.",
            "Join selected IDs to source rows and build a useful filtered table.",
            "Separate the details-panel preference from selection and compare panning, selected-group, box-group, and bounded connected dragging.",
        ),
    ),
    _lesson(
        7,
        "Exploration",
        "search",
        "Find and reveal connections",
        "Find relevant records and reveal their neighborhood without losing the surrounding graph.",
        "NodeAction",
        "guides/selection-search.md",
        "demos/investigation_tools.py",
        (
            "Choose text, label, property, or selector search for a specific question.",
            "Inspect matched records in Python instead of judging a search only by its zoom.",
            "Explore incoming and outgoing neighbors and restore temporary visibility changes.",
        ),
    ),
    _lesson(
        8,
        "Exploration",
        "analysis",
        "Analyze relationships",
        "Answer five different relationship questions with browser-side graph algorithms.",
        "AnalysisAction",
        "guides/analysis.md",
        "demos/investigation_tools.py",
        (
            "Run shortest path, BFS, DFS, connected components, and degree with the required selection.",
            "Interpret each result's IDs, metrics, and displayed-graph scope.",
            "Join algorithm results back to source records without treating connectivity as causality.",
        ),
    ),
    _lesson(
        9,
        "Exploration",
        "expansion",
        "Expand progressively",
        "Load connected records on demand, collapse them again, and preserve the positions already explored.",
        "NodeAction, upsert_elements, delete_elements, ExpansionConfig, ExpansionController, ExpansionOperation, ExpansionProvider, ExpansionRequest, ExpansionResponse, InMemoryExpansionProvider",
        "guides/expansion-visibility.md",
        "demos/branch_expansion.py",
        (
            "Separate source records, loaded cache, and the displayed graph.",
            "Expand independent branches and collapse one while retaining shared and protected records.",
            "Read incremental commands and change records, preserving cached exploration and positions.",
        ),
    ),
    _lesson(
        10,
        "Application workflows",
        "crud",
        "Build CRUD workflows",
        "Validated application changes: choose record types in Python dialogs, then update the Python records and graph. Compare this approval-first workflow with browser drafts.",
        "CrudAction, ElementValidationError, apply_graph_command",
        "guides/crud.md",
        "demos/interactive_crud.py",
        (
            "Turn a CRUD intent into a Python dialog with explicit node or relationship types.",
            "Validate a change before updating Python records and sending its browser command.",
            "Choose approval-first CRUD rather than browser drafts when application rules must run first.",
        ),
    ),
    _lesson(
        11,
        "Application workflows",
        "editing",
        "Edit in the browser",
        "Immediate browser edits: sketch draft nodes and links with undo/redo, then compare their returned changes with the unchanged Python records.",
        "EditAction, ElementsSync",
        "guides/editing-viewport.md",
        "demos/editing_viewport_tools.py",
        (
            "Create, connect, delete, lock, and arrange browser-local drafts with undo and redo.",
            "Read partial edit reports alongside the unchanged Python checkpoint.",
            "Identify when drafts need explicit validation and persistence rather than local history.",
        ),
    ),
    _lesson(
        12,
        "Application workflows",
        "commands",
        "Send graph commands",
        "Send incremental browser instructions and keep Python state synchronized with the same commands.",
        "GraphCommand, GraphCommandValidationError, ElementsSync, add_elements_command, upsert_elements_command, update_data_command, delete_elements_command, set_elements_command, clear_graph_command, viewport_command, apply_graph_command, apply_graph_commands, validate_graph_commands",
        "guides/commands.md",
        "demos/data_helpers_commands.py",
        (
            "Build and send record, layout, and viewport commands to a mounted graph.",
            "Validate and apply data commands to Python as well as the browser.",
            "Choose initial or always synchronization and distinguish command IDs from delivery receipts.",
        ),
    ),
    _lesson(
        13,
        "Application workflows",
        "exports",
        "Export and restore",
        "Export graph records or images and restore a saved set of node positions.",
        "GraphEvent, Layout",
        "guides/events-exports.md",
        "demos/investigation_tools.py",
        (
            "Choose full, visible, selected, image, or position exports for the intended use.",
            "Capture an independent position snapshot and restore coordinates by node ID.",
            "Validate imported positions and distinguish graph data from camera state.",
        ),
    ),
    _lesson(
        14,
        "Advanced",
        "scale",
        "Organize and scale",
        "Compare compound grouping and rendering profiles as the number of connected records grows.",
        "PerformanceProfile, StyleRule",
        "guides/compound-performance.md",
        "demos/compound_performance.py",
        (
            "Group nodes through parent IDs without inventing relationship edges.",
            "Compare default, large, and dense profiles at the same graph size.",
            "Measure actual node and edge counts as the generated dataset grows.",
        ),
    ),
    _lesson(
        15,
        "Advanced",
        "loading",
        "Load larger datasets incrementally",
        "Load bounded batches with cursor-aware requests, acknowledgment, failure recovery, and stable interaction.",
        "ProgressiveLoadConfig, add_elements_command, apply_graph_command",
        "guides/progressive-loading.md",
        "demos/progressive_loading.py",
        (
            "Handle bounded load-more requests using request IDs, cursors, and page sizes.",
            "Merge overlapping records and acknowledge success, failure, and stale requests.",
            "Retry without advancing a failed cursor, finish loading, and restart without remounting.",
        ),
    ),
    _lesson(
        16,
        "Advanced",
        "events",
        "Integrate component events",
        "Connect custom events to callbacks and compare two independent graph instances with changing options.",
        "Event, GraphEvent",
        "recipes/multiple-instances.md",
        "demos/component_v2_validation.py",
        (
            "Define custom listeners and retrieve authoritative records using their target IDs.",
            "Retain the latest payload per action in a Python callback.",
            "Use separate stable keys to isolate two graphs while changing supported live options.",
        ),
    ),
)

# Freeze the legacy filename-based routes before reorganizing their display names.
LAB_PAGES = tuple(
    replace(
        guide,
        area="Feature Lab",
        section="Resources"
        if guide.path == "docs/supported_icons.py"
        else "Playgrounds",
        url_path=guide.url_path or guide.path.rsplit("/", 1)[1].removesuffix(".py"),
    )
    for guide in sorted(
        REFERENCE_AND_DEMO_PAGES, key=lambda guide: guide.section != "Demos"
    )
    if guide.section == "Demos" or guide.path == "docs/supported_icons.py"
)
REFERENCE_PAGES = tuple(
    replace(
        guide,
        url_path=guide.url_path or guide.path.rsplit("/", 1)[1].removesuffix(".py"),
    )
    for guide in REFERENCE_AND_DEMO_PAGES
    if guide.section == "Documentation" and guide.path != "docs/supported_icons.py"
)
PAGE_CATALOG = (*TUTORIAL_PAGES, *LAB_PAGES, *REFERENCE_PAGES)

# New public options require an explicit lesson or compatibility destination.
COMPONENT_OPTION_LESSONS = {
    "elements": 1,
    "layout": 4,
    "node_styles": 3,
    "edge_styles": 3,
    "height": 1,
    "key": 1,
    "on_change": 16,
    "node_actions": 9,
    "crud_actions": 10,
    "edit_actions": 11,
    "viewport_actions": 4,
    "enable_node_actions": 9,
    "events": 16,
    "validate": 1,
    "selection_mode": 6,
    "return_selection": 6,
    "show_selection_details": 6,
    "connected_drag": 6,
    "toolbar": 4,
    "search": 7,
    "analysis_actions": 8,
    "return_positions": 13,
    "performance_profile": 14,
    "min_zoom": 4,
    "max_zoom": 4,
    "wheel_sensitivity": 4,
    "graph_commands": 12,
    "elements_sync": 12,
    "progressive_loading": 15,
    "expansion": 9,
}
ACTION_LESSONS = {
    "NodeAction": (7, 9),
    "CrudAction": (10,),
    "EditAction": (11,),
    "ViewportAction": (4,),
    "AnalysisAction": (8,),
    "SelectionMode": (6,),
    "PerformanceProfile": (14,),
    "ElementsSync": (11, 12),
    "ExpansionOperation": (9,),
}
CAPABILITY_LESSONS = {
    "index.js": 1,
    "graph.js": 6,
    "boxSelection.js": 6,
    "styles.js": 3,
    "search.js": 7,
    "nodeActions.js": 9,
    "toolbox.js": 7,
    "dom.js": 11,
    "expansionBadges.js": 9,
    "analysis.js": 8,
    "crud.js": 10,
    "graphCommands.js": 12,
    "progressiveLoading.js": 15,
    "selectionControls.js": 6,
    "connectedDrag.js": 6,
    "toolbarLayout.js": 4,
    "editTools.js": 11,
    "viewportTools.js / viewbar.js": 4,
    "toolbar.js": 13,
    "graphStats.js / infopanel.js": 6,
    "payloads.js": 16,
    "layouts.js": 4,
    "expansion.js": 9,
    "expansionControls.js": 9,
    "helpers.js / state.js": 16,
}
