name: 'Setup Python Environment'
description: 'Setup python environment and install dependencies'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.x'

runs:
  using: composite
  steps:
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Setup uv
      uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
      with:
        enable-cache: true
    - name: Log Python Version
      shell: bash
      run: python -c "import sys; print(sys.version)"
    - name: Log uv Version
      shell: bash
      run: uv --version
    - name: Install Dependencies
      shell: bash
      run: |
        python_version=$(python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
        uv sync --extra dev --extra docs --frozen --python "$python_version"
        uv run playwright install --with-deps chromium
